Repository graphp/graph, pull requests merged in 2019-10, with the labels that each got.

#172 Minor documentation updates
  README.md
  src/Edge/Base.php
  src/Graph.php
  src/Set/DualAggregate.php
  src/Set/Edges.php
  src/Set/EdgesAggregate.php
  src/Set/Vertices.php
  src/Vertex.php
  src/Walk.php
Labels: easy pick, maintenance

#166 Update package name to graphp/graph and adjust namespace to `Graphp\Graph`
  LICENSE
  README.md
  composer.json
  src/Attribute/AttributeAware.php
  src/Attribute/AttributeBag.php
  src/Attribute/AttributeBagContainer.php
  src/Attribute/AttributeBagNamespaced.php
  src/Attribute/AttributeBagReference.php
  src/Edge/Base.php
  src/Edge/Directed.php
  src/Edge/Undirected.php
  src/Exception.php
  src/Exception/BadMethodCallException.php
  src/Exception/DomainException.php
  src/Exception/InvalidArgumentException.php
  src/Exception/LogicException.php
  src/Exception/NegativeCycleException.php
  src/Exception/OutOfBoundsException.php
  src/Exception/OverflowException.php
  src/Exception/RangeException.php
  src/Exception/RuntimeException.php
  src/Exception/UnderflowException.php
  src/Exception/UnexpectedValueException.php
  src/Exporter/ExporterInterface.php
  src/Graph.php
  src/Set/DualAggregate.php
  src/Set/Edges.php
  src/Set/EdgesAggregate.php
  src/Set/Vertices.php
  src/Set/VerticesAggregate.php
  src/Set/VerticesMap.php
  src/Vertex.php
  src/Walk.php
  tests/Attribute/AbstractAttributeAwareTest.php
  tests/Attribute/AttributeBagContainerTest.php
  tests/Attribute/AttributeBagNamespacedTest.php
  tests/Attribute/AttributeBagReferenceTest.php
  tests/Edge/EdgeAttributesTest.php
  tests/Edge/EdgeBaseTest.php
  tests/Edge/EdgeDirectedTest.php
  tests/Edge/EdgeUndirectedTest.php
  tests/Exception/NegativeCycleExceptionTest.php
  tests/GraphTest.php
  tests/Set/BaseVerticesTest.php
  tests/Set/EdgesTest.php
  tests/Set/VerticesMapTest.php
  tests/Set/VerticesTest.php
  tests/TestCase.php
  tests/VertexTest.php
  tests/WalkTest.php
Labels: BC break, maintenance

#173 Add `AttributeAware::removeAttribute()`
  src/Attribute/AttributeAware.php
  src/Attribute/AttributeBag.php
  src/Attribute/AttributeBagContainer.php
  src/Attribute/AttributeBagNamespaced.php
  src/Attribute/AttributeBagReference.php
  src/Edge/Base.php
  src/Graph.php
  src/Vertex.php
  tests/Attribute/AbstractAttributeAwareTest.php
Labels: BC break, new feature

#175 Move creating edges to `Graph`
  README.md
  src/Edge/Directed.php
  src/Edge/Undirected.php
  src/Graph.php
  src/Vertex.php
  tests/Edge/EdgeAttributesTest.php
  tests/Edge/EdgeBaseTest.php
  tests/Edge/EdgeDirectedTest.php
  tests/Edge/EdgeUndirectedTest.php
  tests/GraphTest.php
  tests/Set/EdgesTest.php
  tests/TestCase.php
  tests/VertexTest.php
  tests/WalkTest.php
Labels: BC break, new feature

#176 Remove uneeded ExporterInterface
  src/Exporter/ExporterInterface.php
Labels: BC break, easy pick

#177 Remove edge cloning alias methods, use Graph instead
  src/Edge/Base.php
  src/Walk.php
  tests/Edge/EdgeBaseTest.php
  tests/GraphTest.php
  tests/WalkTest.php
Labels: BC break

#178 Rename Edge classes to Edge, EdgeUndirected and EdgeDirected
  src/Edge.php
  src/EdgeDirected.php
  src/EdgeUndirected.php
  src/Graph.php
  src/Set/Edges.php
  src/Vertex.php
  src/Walk.php
  tests/EdgeAttributesTest.php
  tests/EdgeBaseTest.php
  tests/EdgeDirectedTest.php
  tests/EdgeUndirectedTest.php
  tests/Set/EdgesTest.php
  tests/TestCase.php
Labels: BC break, new feature

#179 Replace `ORDER_RANDOM` with `getVerticesShuffled()`, `getVertexRandom()`, `getEdgesShuffled()` and `getEdgeRandom()`
  src/Set/Edges.php
  src/Set/Vertices.php
  tests/Set/BaseVerticesTest.php
  tests/Set/EdgesTest.php
Labels: BC break, new feature

#180 Support ordering vertices and edges by arbitrary attribute names
  src/Set/Edges.php
  src/Set/Vertices.php
  src/Walk.php
  tests/Set/BaseVerticesTest.php
  tests/Set/EdgesTest.php
  tests/Set/VerticesTest.php
  tests/WalkTest.php
Labels: new feature

#181 Support ordering vertices and edges by custom callbacks, remove all `ORDER_*` consts
  src/Set/Edges.php
  src/Set/Vertices.php
  src/Walk.php
  tests/Set/BaseVerticesTest.php
  tests/Set/EdgesTest.php
  tests/Set/VerticesTest.php
  tests/WalkTest.php
Labels: BC break, new feature

#182 Remove all mathematical properties, use generic attributes instead
  src/Edge.php
  src/Graph.php
  src/Vertex.php
  tests/EdgeAttributesTest.php
  tests/GraphTest.php
  tests/Set/BaseVerticesTest.php
  tests/Set/EdgesTest.php
  tests/TestCase.php
  tests/VertexTest.php
  tests/WalkTest.php
Labels: BC break, new feature

#183 Support native cloning of `Graph` object, remove all methods related to cloning and accessing cloned objects
  src/Graph.php
  tests/GraphTest.php
Labels: BC break, new feature
