Repository graphp/graph, pull requests merged in 2020-08, with the labels that each got.

#193 Remove all custom Exception classes, use built-in Exceptions instead
  src/Edge.php
  src/EdgeDirected.php
  src/EdgeUndirected.php
  src/Exception/BadMethodCallException.php
  src/Exception/DomainException.php
  src/Exception/InvalidArgumentException.php
  src/Exception/LogicException.php
  src/Exception/NegativeCycleException.php
  src/Exception/OutOfBoundsException.php
  src/Exception/OverflowException.php
  src/Exception/RangeException.php
  src/Exception/RuntimeException.php
  src/Exception/UnderflowException.php
  src/Exception/UnexpectedValueException.php
  src/Graph.php
  src/Set/Edges.php
  src/Set/Vertices.php
  src/Vertex.php
  src/Walk.php
  tests/Exception/NegativeCycleExceptionTest.php
Labels: BC break, new feature

#194 Remove left-over namespaced Exception interface
  src/Exception.php
Labels: BC break, easy pick, new feature

#192 Run tests on PHPUnit 9, on PHP 7.4 and add .gitattributes to exclude dev files from exports
  .gitattributes
  .travis.yml
  composer.json
  phpunit.xml.dist
  phpunit.xml.legacy
  tests/EdgeTest.php
  tests/EntityTest.php
  tests/GraphTest.php
  tests/Set/EdgesTest.php
  tests/Set/VerticesTest.php
  tests/TestCase.php
  tests/VertexTest.php
  tests/WalkTest.php
Labels: maintenance

#195 Remove `Vertices` and `Edges` collection classes, use plain arrays instead
  src/Edge.php
  src/EdgeDirected.php
  src/EdgeUndirected.php
  src/Graph.php
  src/Set/DualAggregate.php
  src/Set/Edges.php
  src/Set/EdgesAggregate.php
  src/Set/Vertices.php
  src/Set/VerticesAggregate.php
  src/Vertex.php
  src/Walk.php
  tests/EdgeDirectedTest.php
  tests/EdgeTest.php
  tests/EdgeUndirectedTest.php
  tests/GraphTest.php
  tests/Set/EdgesTest.php
  tests/Set/VerticesTest.php
  tests/TestCase.php
  tests/VertexTest.php
  tests/WalkTest.php
Labels: BC break, new feature
