Repository graphp/graph, pull requests merged in 2021-12, with the labels that each got.

#207 Use GitHub Actions for continuous integration (CI) for legacy v0.9.x
  .gitattributes
  .github/workflows/ci.yml
  .travis.yml
  README.md
Labels: maintenance

#204 Fix automatic vertex ID generation when using vertex IDs with strings
  src/Graph.php
  tests/GraphTest.php
Labels: bug

#208 Support PHP 8.1 release
  .github/workflows/ci.yml
  README.md
  phpunit.xml.dist
  src/Set/Edges.php
  src/Set/Vertices.php
Labels: new feature

#209 Add badges to show number of project installations
  README.md
Labels: maintenance
